import { PublicShell } from '../components/AppShell';

export default function PrivacyPage() {
  return <PublicShell><article className="legal-page">
    <p className="eyebrow">CONFIDENTIALITÉ & RGPD</p><h1>Confidentialité & gestion de vos données</h1>
    <p>Cette application est conçue pour le pilotage financier personnel. Elle peut stocker des revenus, dépenses, informations de salaire, investissements, éléments fiscaux, immobilier, dettes, objectifs et préférences. Nous cherchons à ne collecter que les informations nécessaires aux fonctions que vous utilisez.</p>
    <h2>Pourquoi ces données sont-elles traitées ?</h2><p>Pour calculer vos indicateurs, vérifier des incohérences de paie, simuler des scénarios, suivre vos objectifs, préparer des repères fiscaux et personnaliser localement des alertes. Les données ne servent pas au ciblage publicitaire.</p>
    <h2>Où sont-elles stockées ?</h2><p>Les données applicatives sont prévues dans Cloud Firestore, dans une localisation européenne choisie lors de la création du projet. La localisation exacte doit être consignée par l’exploitant avant la mise en production. L’application ne prétend pas être « 100 % France » : certains services Google, mécanismes d’authentification, réseaux ou opérations de support peuvent impliquer des traitements hors de la seule France selon les conditions des fournisseurs.</p>
    <h2>Services utilisés</h2><p>Google/Firebase fournit l’authentification, Firestore, App Check et l’hébergement lorsqu’ils sont activés. GitHub héberge le code et exécute la CI/CD ; le dépôt ne doit contenir aucune donnée financière utilisateur. Le pipeline d’actualités interroge uniquement des sources publiques officielles et ne leur transmet pas votre profil financier.</p>
    <h2>Intelligence artificielle externe</h2><p>Le mode par défaut est fondé sur des règles locales. L’analyse IA externe est désactivée. Si un fournisseur est ajouté, l’application doit afficher les catégories de données envoyées, le fournisseur et la finalité, puis recueillir un consentement explicite, révocable et désactivable. Aucune fiche de paie ne doit être envoyée automatiquement à un tiers.</p>
    <h2>Durée de conservation</h2><p>Par défaut, les données sont conservées tant que le compte existe. Les historiques optionnels peuvent avoir une durée configurable. Les informations fiscales ne doivent pas être supprimées automatiquement sans avertissement, car elles peuvent être nécessaires pour justifier des reports ou contrôles ultérieurs.</p>
    <h2>Vos droits et contrôles</h2><p>Dans « Mes données », un utilisateur autorisé peut générer un export JSON à la demande, supprimer des historiques ciblés ou effacer les données financières de son espace. L’export est créé dans le navigateur et son URL temporaire est révoquée immédiatement après le téléchargement.</p>
    <p>La suppression du compte Auth peut être demandée après confirmation renforcée. L’entrée d’allowlist est volontairement non modifiable par l’utilisateur ; sa suppression nécessite une action administrative privilégiée afin de ne pas affaiblir le modèle d’autorisation. Cette limite opérationnelle doit être traitée par l’exploitant lors d’un effacement complet.</p>
    <h2>Cookies et mesure d’audience</h2><p>Aucun tracking marketing n’est prévu par défaut. Aucune bannière de cookies non essentiels n’est ajoutée tant qu’aucun traceur non essentiel n’est utilisé. Toute mesure d’audience facultative doit être désactivée par défaut et ne doit jamais recevoir de salaire, montant, patrimoine, adresse, transaction ou donnée fiscale.</p>
    <h2>Sécurité</h2><p>Les accès aux données sont filtrés par Firebase Authentication, une allowlist séparée et des règles Firestore « deny by default ». Le transport est chiffré par HTTPS. App Check ajoute une barrière supplémentaire lorsqu’il est activé, sans remplacer les règles d’autorisation.</p>
    <p className="fine-print">Cette page décrit le comportement prévu par le dépôt. L’exploitant reste responsable de renseigner son identité, ses coordonnées de contact, la localisation réelle des services, les durées retenues et toute information juridique requise avant ouverture à des tiers.</p>
  </article></PublicShell>;
}
