import { useMemo, useState } from 'react';
import { Money } from '../components/Money';
import { DEFAULT_BUY_VS_RENT_SCENARIOS, simulateBuyVsRent } from '../realEstate/buyVsRent';
import { purchaseCapacity } from '../realEstate/capacity';
import { dpeRentalStatus } from '../realEstate/dpeRules';
import { mortgage } from '../realEstate/mortgage';

export default function RealEstatePage() {
  const [credit, setCredit] = useState({ principal: '250000', rate: '3.5', insurance: '0.3', years: '20' });
  const loan = useMemo(() => {
    try { return mortgage({ principal: Number(credit.principal), annualRate: Number(credit.rate) / 100, insuranceAnnualRate: Number(credit.insurance) / 100, termMonths: Number(credit.years) * 12 }); } catch { return null; }
  }, [credit]);
  const [buy, setBuy] = useState({ price: '300000', down: '50000', rent: '1200', horizon: '15' });
  const scenarios = useMemo(() => {
    try {
      return DEFAULT_BUY_VS_RENT_SCENARIOS.map((scenario) => simulateBuyVsRent({ purchasePrice: Number(buy.price), downPayment: Number(buy.down), mortgageAnnualRate: 0.035, insuranceAnnualRate: 0.003, termMonths: 240, notaryFees: Number(buy.price) * 0.075, initialWorks: 0, annualPropertyTax: 1800, annualOwnerCharges: 1800, annualMaintenance: Number(buy.price) * 0.005, currentMonthlyRent: Number(buy.rent), horizonYears: Number(buy.horizon) }, scenario));
    } catch { return []; }
  }, [buy]);
  const capacity = useMemo(() => purchaseCapacity({ stableMonthlyIncome: 3500, otherStableMonthlyIncome: 0, monthlyDebtPayments: 0, monthlyRecurringCharges: 0, maxDebtServiceRatio: 0.35, annualRate: 0.035, insuranceAnnualRate: 0.003, termMonths: 240, availableSavings: 60000, reserveToKeep: 15000, acquisitionCostRate: 0.075 }), []);
  return <>
    <section className="page-heading"><div><p className="eyebrow">IMMOBILIER</p><h1>Acheter, louer, financer : comparer les hypothèses.</h1><p>L’outil ne répond jamais simplement « achète » ou « loue ». Il expose le coût du crédit, les scénarios et les variables sensibles.</p></div></section>
    <section className="split-grid"><article className="panel"><div className="panel-heading"><h2>Crédit immobilier</h2></div><div className="form-grid"><label>Capital €<input value={credit.principal} onChange={(e) => setCredit({ ...credit, principal: e.target.value })} /></label><label>Taux annuel %<input value={credit.rate} onChange={(e) => setCredit({ ...credit, rate: e.target.value })} /></label><label>Assurance annuelle %<input value={credit.insurance} onChange={(e) => setCredit({ ...credit, insurance: e.target.value })} /></label><label>Durée années<input value={credit.years} onChange={(e) => setCredit({ ...credit, years: e.target.value })} /></label></div>{loan ? <div className="result-stack"><div className="hero-amount"><span>Mensualité crédit + assurance</span><Money value={loan.monthlyPayment} /></div><div className="ledger-row"><span>Intérêts totaux</span><Money value={loan.totalInterest} /></div><div className="ledger-row"><span>Assurance totale</span><Money value={loan.totalInsurance} /></div></div> : <p className="error">Paramètres invalides.</p>}</article>
      <article className="panel"><div className="panel-heading"><h2>Capacité indicative</h2><span className="badge">EXEMPLE MODIFIABLE DANS LE MOTEUR</span></div><div className="ledger-row"><span>Budget achat indicatif</span><Money value={capacity.indicativePurchasePrice} /></div><div className="ledger-row"><span>Emprunt indicatif</span><Money value={capacity.borrowingCapacity} /></div><div className="ledger-row"><span>Apport utilisable</span><Money value={capacity.usableContribution} /></div><div className="ledger-row"><span>Réserve conservée</span><Money value={capacity.reserveKept} /></div><p className="fine-print">{capacity.warning} L’outil n’utilise jamais automatiquement toute l’épargne comme apport.</p></article></section>
    <section className="panel"><div className="panel-heading"><h2>Achat vs location</h2><span className="muted">Prudent · Central · Optimiste</span></div><div className="form-grid compact"><label>Prix €<input value={buy.price} onChange={(e) => setBuy({ ...buy, price: e.target.value })} /></label><label>Apport €<input value={buy.down} onChange={(e) => setBuy({ ...buy, down: e.target.value })} /></label><label>Loyer mensuel €<input value={buy.rent} onChange={(e) => setBuy({ ...buy, rent: e.target.value })} /></label><label>Horizon années<input value={buy.horizon} onChange={(e) => setBuy({ ...buy, horizon: e.target.value })} /></label></div><div className="scenario-grid">{scenarios.map((result) => <article className="scenario" key={result.scenario.name}><strong>{result.scenario.name}</strong><p>{result.breakEvenYear === null ? 'Pas de seuil constaté sur l’horizon.' : `Seuil indicatif : année ${result.breakEvenYear}.`}</p><small>Immobilier {(result.scenario.propertyGrowthRate * 100).toFixed(1)} %/an · alternative {(result.scenario.alternativeReturnRate * 100).toFixed(1)} %/an</small></article>)}</div><p className="fine-print">Les frais, rendements et évolutions sont des hypothèses de scénario. Modifier les hypothèses avant toute conclusion.</p></section>
    <section className="panel"><div className="panel-heading"><h2>DPE / location</h2><span className="muted">Règles versionnées</span></div>{['E', 'F', 'G'].map((dpe) => { const status = dpeRentalStatus(dpe, new Date()); return <div className="ledger-row" key={dpe}><span>DPE {dpe}</span><span>{status.message}</span></div>; })}<p className="fine-print">Source officielle référencée dans le moteur. Les exceptions et autres critères de décence restent à vérifier.</p></section>
  </>;
}
